name: EduRec
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.19.5
  - pandas=1.1.5
  - psycopg2=2.8.6
  - python-dotenv=1.0.1
  - scikit-surprise=1.1.1
  - surprise=0.1
  - tensorflow=2.4.0
  - redis=5.0.3
  - redis-py=3.5.3
